  version: "3"
  services:
    app:
      build: .
      container_name: flask_app
      ports:
        - 8000:8000
      restart: always
      depends_on:
        - db
        - redis
    db:
      image: postgres:9.5
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=testdb
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
    redis:
      image: redis:4.0.5-alpine     
    client1:
      container_name: client1
      build:
        context: ./client/client-consent-app
        dockerfile: Dockerfile
      ports:
        - 3001:80
    client2:
      container_name: client2
      build:
        context: ./client/data-collection
        dockerfile: Dockerfile
      ports:
        - 3002:80
    client3:
      container_name: client3
      build:
        context: ./client/data-dissemination
        dockerfile: Dockerfile
      ports:
        - 3003:80          
    client4:
      container_name: client4
      build:
        context: ./client/data-demo
        dockerfile: Dockerfile
      ports:
        - 3004:80                     
  volumes:
    pgdata:

